sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.0
  - 2.3.0
before_install:
  - openssl aes-256-cbc -K $encrypted_121e786cd5aa_key -iv $encrypted_121e786cd5aa_iv -in .gcp-keyfile.json.enc -out .gcp-keyfile.json -d
  - gem install bundler -v 1.12.1
env:
  global:
  - secure: UDesPsjI5LZhaQCI1C5avo3+9vP3snnT1X8FXNzYIG6dABsXhvy8H2Kfia5uQXFty1LuXhORm/xSfGTMx8ybZI0Gc7sGHzP7s6gZ8m17TlzhdxTnKJwqqCf+8/FVlxWbrHeRkA5fVEnCRJw1IU7E4ys9/ExbJBPLjm5E0WSwDQoYicJvkEd4hSvNxnydm2NdA6k1D0Hy8/gTIgXVjQFWbXnh1btiVXKsyN9PkTvvPbz6Q8XY6SpS8W1V9vwBUllJduzO3uVLNjW3LgTFL2g4qUX4ilCy9NaLUniGXye6NpiRy+//gO+N6R83S5o783ZO//2K9kC87a5ZLcy4E1Oc7jMT5AmN1vsKlztsJqw+iDDVXZhGN1w56dDOt+xpx5jWNo03LKzTjpUCCfX7hWZeDbftZfqKMfwQFFD9xz05EvKu8ZpnPCKlveh3wFaHYhGsF469nZb8K7p1TUWRsVl4YjxEro6KaMcNvSOucO8jABqzNTEtrAryAM9lrUBLzpIa/YtxISeOdKNimotxRXiHe2T4x9/PrxQE6DX+UNxxhYUogYxd0qR5E6NumUHhlCEIuaRmoUXV6RXML16/FAolMl6pdszsLhj3SGiX9PXws4lsTNk5M32sTVCqk/lmsilMdyApMtX017ELy6Q6Eiv+xcIUciaAWo3md+z4DN4rnuw=
  - secure: X+XWoTjr/j4SZeE6q2geD7dMVxFCNpkSeCOzfcMkER14cZDeryed0b8XsCOMgGiPvaREhl6/zCmqjDJG+qv2JmL/Cv7itvxzbLJ1VV4yUgBZhF8Rw0XcyRxeTdZINupaXYqm3YWMeAIswCXzOYCREspotADsTCHEr0DXCJuWT3X7R/bDrdb3D//5DZxNtjHotQfahpwWVbgG0dpHgXkSNkcHUNtGcRrpMIq65IADaFaIb5me/xRidJsWM+l4wnIrKxKjckHdoi6Mh03Gc5knbrw3D1U4z5QQl/HXzrZ9TYmh2oFqHizaK4knf0nCLpmQhAXL0wx2jiwv3xQfePkWqFc09nuWpMB8fRaPJVvQcC78EJlpLC9BrBGAmDtid6H9q9RXW1Qp1oWIy3mUs6MSvZ+TlctIG7ENfPlU98Vvi8+UovmZoiJ5BZiGqFgK2gfCjeQgpbHZ8h8yhxtKPktFiO6z4nsL1GR8NxvqRrvmETgVYjswVP4NXx5SKEom06Q1MUHoFsj0Y5OV4HROd7+DlBdX4Tm+jTjQeBizcvfVCaH9PmPmvTKOs9w230wswONRlQy1Ajz6DhwgIq/pK5vLLlwgrobeC9amRIi2T4XQje34Aoh7+xMvU5I1pP9xXf/pSqUY+7Pc2YukbeuYhNxvBupTZ5geG3g7TaQDW9JS7+4=
